package com.uren.siirler.Constants;

import com.uren.siirler.R;

public class NumericConstants {

    public static int[] profileSoruceArray = {
            R.drawable.img1_a_kadir,
            R.drawable.img2_a_kadir_bilgin,
            R.drawable.img3_abdurrahim_karakoc,
            R.drawable.img4_adnan_ozer,
            R.drawable.img5_adnan_yucel,
            R.drawable.img6_afsar_timucin,
            R.drawable.img7_ahmed_arif,
            R.drawable.img8_ahmet_ada,
            R.drawable.img9_ahmet_erhan,
            R.drawable.img10_ahmet_hamdi_tanpinar,
            R.drawable.img11_ahmet_hasim,
            R.drawable.img12_ahmet_hulusi_cekic,
            R.drawable.img13_ahmet_kutsi_tecer,
            R.drawable.img14_ahmet_muhip_dranas,
            R.drawable.img15_ahmet_oktay,
            R.drawable.img16_ahmet_ozer,
            R.drawable.img17_ahmet_selcuk_ilhan,
            R.drawable.img18_ahmet_telli,
            R.drawable.img19_ahmet_unal_cam,
            R.drawable.img20_ahmet_uysal,
            R.drawable.img21_akgun_akova,
            R.drawable.img22_ali_puskulluoglu,
            R.drawable.img23_ali_yuce,
            R.drawable.img24_arif_damar,
            R.drawable.img25_arif_nihat_asya,
            R.drawable.img26_arkadas_ozger,
            R.drawable.img27_asaf_halet_celebi,
            -1,
            R.drawable.img29_ataol_behramoglu,
            R.drawable.img30_atilla_ilhan,
            R.drawable.img31_aysenur_yazici,
            R.drawable.img32_aziz_nesin,
            R.drawable.img33_bahaettin_karakoc,
            R.drawable.img34_baki_suha_ediboglu,
            R.drawable.img35_bedirhan_gokce,
            R.drawable.img36_bedri_rahmi_eyuboglu,
            R.drawable.img37_behcet_aysan,
            R.drawable.img38_behcet_necatigil,
            R.drawable.img39_bekir_sitki_erdogan,
            -1,
            R.drawable.img141_ozdemir_ince,
            R.drawable.img42_cahit_irgat,
            R.drawable.img43_cahit_kulebi,
            R.drawable.img44_cahit_sitki_taranci,
            R.drawable.img45_can_dundar,
            R.drawable.img46_can_yucel,
            R.drawable.img47_cavidan_tumerkan,
            R.drawable.img48_celal_silay,
            R.drawable.img49_celal_vardar,
            -1,
            R.drawable.img51_cemal_safi,
            R.drawable.img52_cemal_sureya,
            R.drawable.img53_cenap_sahabettin,
            R.drawable.img54_cevat_capan,
            R.drawable.img55_cevdet_aslangul,
            R.drawable.img56_cevdet_kudret_solok,
            R.drawable.img57_ceyhun_atuf_kansu,
            R.drawable.img58_cezmi_ersoz,
            -1,
            R.drawable.img60_dilaver_cebeci,
            R.drawable.img61_edip_cansever,
            -1,
            R.drawable.img63_enis_behic_koryurek,
            -1,
            R.drawable.img65_enver_gokce,
            R.drawable.img66_erdem_beyazit,
            R.drawable.img67_erdogan_alkan,
            -1,
            R.drawable.img69_faruk_nafiz_camlibel,
            R.drawable.img70_fazil_husnu_daglarca,
            R.drawable.img71_ferman_kacman,
            R.drawable.img72_feyzi_halici,
            -1,
            -1,
            R.drawable.img75_gulseli_inal,
            R.drawable.img76_gultekin_samanoglu,
            R.drawable.img77_gulten_akin,
            R.drawable.img78_halide_nusret_zorlutuna,
            R.drawable.img79_halil_soyuer,
            R.drawable.img80_halim_yagcioglu,
            R.drawable.img81_halit_fahri_ozansoy,
            R.drawable.img82_hasan_ali_yucel,
            R.drawable.img83_hasan_huseyin_korkmaz,
            R.drawable.img84_hasan_simsek,
            R.drawable.img85_haydar_erulgen,
            R.drawable.img86_hilmi_yavuz,
            R.drawable.img87_huseyin_nihal_atsiz,
            R.drawable.img88_huseyin_yurttas,
            R.drawable.img89_husrev_hatemi,
            R.drawable.img90_ibrahim_sadri,
            R.drawable.img91_ibrahim_zeki_burdurlu,
            R.drawable.img92_ilhan_gecer,
            R.drawable.img93_ismet_ozel,
            -1,
            R.drawable.img95_kahraman_tazeoglu,
            -1,
            R.drawable.img97_kemalettin_kamu,
            R.drawable.img98_kerem_aydin_erdem,
            R.drawable.img99_kucuk_iskender,
            R.drawable.img100_lale_mudur,
            -1,
            R.drawable.img102_mehmet_akif_ersoy,
            -1,
            R.drawable.img104_melih_cevdet_anday,
            R.drawable.img105_metin_altiok,
            R.drawable.img106_metin_demirtas,
            R.drawable.img107_metin_eloglu,
            R.drawable.img108_muammer_erkul,
            R.drawable.img109_mumtaz_begen,
            R.drawable.img110_munis_faik_ozansoy,
            R.drawable.img111_nahit_kayabas,
            -1,
            R.drawable.img113_nahit_ulvi_akgun,
            -1,
            R.drawable.img115_nazim_hikmet,
            R.drawable.img116_necati_cumali,
            R.drawable.img117_necdet_evliyagil,
            R.drawable.img118_necip_fazil_kisakurek,
            R.drawable.img119_necla_marasli,
            R.drawable.img120_necmettin_halil_oran,
            R.drawable.img121_nevzat_celik,
            -1,
            R.drawable.img123_neyzen_tevfik,
            R.drawable.img124_nihat_behram,
            R.drawable.img125_nurettin_durman,
            -1,
            R.drawable.img127_nuri_can,
            R.drawable.img128_nurullah_genc,
            R.drawable.img129_oguz_tansel,
            R.drawable.img130_oguzkan_bolukbasi,
            R.drawable.img131_oktay_rifat_horozcu,
            R.drawable.img132_omer_bedrettin_usakli,
            R.drawable.img133_onat_kutlar,
            R.drawable.img134_orhan_saik_gokyay,
            R.drawable.img135_orhan_seyfi_orhon,
            R.drawable.img136_orhan_veli_kanik,
            R.drawable.img137_orhon_murat_ariburnu,
            R.drawable.img138_oruc_aruba,
            R.drawable.img139_osman_yuksel_serdengecti,
            R.drawable.img140_ozdemir_asaf,
            R.drawable.img141_ozdemir_ince,
            R.drawable.img142_ozel_arabul,
            -1,
            R.drawable.img144_pelin_onay,
            R.drawable.img145_refik_durbas,
            -1,
            R.drawable.img147_rifat_ilgaz,
            R.drawable.img148_riza_tevfik_bolukbasi,
            R.drawable.img149_sabahattin_ali,
            R.drawable.img150_sabahattin_kudret_aksal,
            -1,
            R.drawable.img152_sait_faik_abasiyanik,
            R.drawable.img153_semsi_belli,
            R.drawable.img154_sennur_sezer,
            R.drawable.img155_serdar_tuncer,
            R.drawable.img156_sezai_karakoc,
            R.drawable.img157_sinasi_ozdenoglu,
            R.drawable.img158_sitki_yircali,
            R.drawable.img159_sukran_kurdakulu,
            R.drawable.img160_sukru_erbas,
            R.drawable.img161_sukufe_nihal,
            R.drawable.img162_sunay_akin,
            R.drawable.img163_sureyya_berfe,
            R.drawable.img164_tayfun_talipoglu,
            R.drawable.img165_tekin_gonenc,
            R.drawable.img166_tevfik_fikret,
            R.drawable.img167_timucin_ozyurekli,
            R.drawable.img168_turgut_uyar,
            R.drawable.img169_turhan_oguzbas,
            R.drawable.img170_turkan_ildeniz,
            R.drawable.img171_ugur_arslan,
            R.drawable.img172_ulku_tamer,
            R.drawable.img173_umit_yasar_oguzcan,
            R.drawable.img174_yagmur_atsiz,
            R.drawable.img175_yahya_kemal_bayatli,
            R.drawable.img176_yasar_nabi_nayir,
            R.drawable.img177_yavuz_bulent_bakiler,
            R.drawable.img178_yilmaz_aybar,
            R.drawable.img179_yilmaz_erdogan,
            R.drawable.img180_yilmaz_odabasi,
            R.drawable.img181_yuksel_satoglu,
            R.drawable.img182_yusuf_hayaloglu,
            R.drawable.img183_yusuf_ziya_ortac,
            R.drawable.img184_ziya_osman_saba

    };

    //siir sayilari

    public static final int NUMBER_OF_HORIZONTAL_POEMS = 10;
    public static final int NUMBER_OF_VERTICAL_POEMS = 50;
    public static final int NUMBER_OF_SUGGESTED_POEMS = 1;

    //SinglePoemFragment variables
    public static final int COMING_FROM_DAILY_POPULAR_POEM = 0;
    public static final int COMING_FROM_NORMAL_POEM = 1;

    //Banner item cnt
    public static final int ITEM_PER_AD = 4;

}
